namespace Imprelia.PrintAgent.Localization;

/// <summary>Tablas de texto ES/EN. Get() cae a ES y luego a la clave si falta.</summary>
internal static class Strings
{
    public static string Get(string lang, string key)
    {
        var table = lang == "en" ? En : Es;
        if (table.TryGetValue(key, out var v)) return v;
        if (Es.TryGetValue(key, out var es)) return es;
        return key;
    }

    private static readonly Dictionary<string, string> Es = new()
    {
        // Común
        ["common.save"] = "Guardar",
        ["common.cancel"] = "Cancelar",
        ["common.edit"] = "Editar",
        ["common.delete"] = "Eliminar",
        ["common.remove"] = "Quitar",
        ["common.new"] = "Nueva",
        ["common.test"] = "Probar",

        // Sidebar / nav
        ["sidebar.subtitle"] = "Print Agent",
        ["sidebar.active"] = "Agente activo",
        ["sidebar.version"] = "Versión",
        ["sidebar.port"] = "Puerto",
        ["nav.dashboard"] = "Dashboard",
        ["nav.printers"] = "Impresoras",
        ["nav.routes"] = "Rutas",
        ["nav.settings"] = "Configuración",
        ["nav.logs"] = "Logs",
        ["nav.bridge"] = "Remote Bridge",
        ["nav.client"] = "Impresión remota",

        // Footer
        ["footer.secure"] = "Seguro y local",
        ["footer.listening"] = "El agente escucha en",
        ["footer.bydefault"] = "por defecto",
        ["footer.apiGuide"] = "📖 Guía API",
        ["footer.minimize"] = "⊟ Minimizar",
        ["footer.exit"] = "⏻ Salir",

        // Dashboard
        ["dash.title"] = "Dashboard",
        ["dash.subtitle"] = "Estado general del agente de impresión.",
        ["dash.agentStatus"] = "Estado del agente",
        ["dash.runningOk"] = "El agente está funcionando correctamente.",
        ["dash.httpPort"] = "Puerto HTTP",
        ["dash.version"] = "Versión",
        ["dash.localUrl"] = "URL local",
        ["dash.status"] = "Estado",
        ["dash.quickActions"] = "Acciones rápidas",
        ["dash.copyUrl"] = "Copiar URL",
        ["dash.copyEndpoint"] = "Copiar endpoint",
        ["dash.printTest"] = "Imprimir prueba",
        ["dash.printersDetected"] = "Impresoras detectadas",
        ["dash.viewAll"] = "Ver todas →",
        ["dash.routesConfigured"] = "Rutas configuradas",
        ["dash.recentEvents"] = "Últimos eventos",
        ["dash.viewLogs"] = "Ver logs →",
        ["dash.quickSummary"] = "Resumen rápido",
        ["dash.active"] = "Activo",
        ["dash.uptime"] = "Uptime",
        ["dash.printers"] = "Impresoras",
        ["dash.noPrinter"] = "(sin impresora)",

        // Impresoras
        ["printers.title"] = "Impresoras instaladas",
        ["printers.subtitle"] = "Administra tus impresoras: detecta, prueba y selecciona la predeterminada.",
        ["printers.refresh"] = "↻ Actualizar lista",
        ["printers.setDefault"] = "⊕ Usar como predeterminada",
        ["printers.printTest"] = "🖨 Imprimir prueba",
        ["printers.colName"] = "Nombre",
        ["printers.colStatus"] = "Estado",
        ["printers.colType"] = "Tipo",
        ["printers.colCaps"] = "Capacidades",
        ["printers.colDefault"] = "Predeterminada",
        ["printers.colActions"] = "Acciones",
        ["printers.online"] = "En línea",
        ["printers.defaultBadge"] = "✓ Predeterminada",
        ["printers.detailTitle"] = "Detalles de la impresora",
        ["printers.selectPrompt"] = "Selecciona una impresora para ver sus detalles",
        ["printers.capsSupported"] = "Capacidades soportadas",
        ["printers.defaultYes"] = "✓ Sí",
        ["printers.source"] = "Fuente",
        ["printers.setDefaultBtn"] = "★ Usar como predeterminada",

        // Rutas
        ["routes.title"] = "Rutas por propósito",
        ["routes.subtitle"] = "Cada propósito envía el contenido a una impresora específica y en el formato adecuado.",
        ["routes.new"] = "+ Nueva ruta",
        ["routes.edit"] = "Editar",
        ["routes.test"] = "Probar",
        ["routes.delete"] = "Eliminar",
        ["routes.colPurpose"] = "Propósito",
        ["routes.colPrinter"] = "Impresora",
        ["routes.colType"] = "Tipo",
        ["routes.colStatus"] = "Estado",
        ["routes.colActions"] = "Acciones",
        ["routes.active"] = "Activa",
        ["routes.unassigned"] = "(sin asignar)",
        ["routes.selectPrompt"] = "Selecciona una ruta para ver sus detalles",
        ["routes.editTitle"] = "Editar ruta",
        ["routes.newTitle"] = "Nueva ruta",
        ["routes.purposeLabel"] = "Propósito",
        ["routes.purposeHint"] = "Solo letras, números y guiones bajos",
        ["routes.printerLabel"] = "Impresora",
        ["routes.typeLabel"] = "Tipo de contenido",
        ["routes.detailTitle"] = "Detalles de la ruta seleccionada",
        ["routes.saveBtn"] = "Guardar ruta",
        ["routes.cancelBtn"] = "Cancelar",
        ["routes.footerHint"] = "💡 Ejemplos: ticket, kitchen_order, report, label, fiscal. Solo letras, números y guiones bajos.",
        ["routes.validations"] = "Validaciones recomendadas",
        ["routes.val1"] = "El propósito debe ser único.",
        ["routes.val2"] = "La impresora debe estar disponible.",
        ["routes.val3"] = "El tipo debe coincidir con la app.",
        ["routes.testThis"] = "▷ Probar esta ruta",

        // Configuración
        ["settings.title"] = "Configuración del agente",
        ["settings.subtitle"] = "Ajusta las preferencias de red, seguridad e inicio del agente.",
        ["settings.network"] = "Red y conexión",
        ["settings.networkSub"] = "Configura el puerto de escucha del agente.",
        ["settings.httpPort"] = "Puerto HTTP",
        ["settings.portHint"] = "El agente escucha en 127.0.0.1 por defecto. Solo conexiones locales serán aceptadas.",
        ["settings.cors"] = "CORS y orígenes permitidos",
        ["settings.corsSub"] = "Define qué sitios web pueden comunicarse con el agente.",
        ["settings.allowCors"] = "Permitir CORS",
        ["settings.origins"] = "Orígenes permitidos (uno por línea)",
        ["settings.originsHint"] = "Si la lista queda vacía, se permite cualquier origen.",
        ["settings.startup"] = "Inicio de Windows",
        ["settings.startupSub"] = "Controla el comportamiento al iniciar el sistema.",
        ["settings.autostart"] = "Abrir automáticamente al iniciar Windows",
        ["settings.language"] = "Idioma",
        ["settings.languageSub"] = "Idioma de la interfaz.",
        ["settings.langEs"] = "Español",
        ["settings.langEn"] = "English",
        ["settings.save"] = "Guardar cambios",

        // Logs
        ["logs.title"] = "Logs del agente",
        ["logs.subtitle"] = "Consulta la actividad del agente para diagnóstico y solución de problemas.",
        ["logs.level"] = "Nivel:",
        ["logs.all"] = "Todos",
        ["logs.info"] = "Info",
        ["logs.warning"] = "Warning",
        ["logs.error"] = "Error",
        ["logs.autoRefresh"] = "Auto-actualizar",
        ["logs.colTime"] = "Fecha / Hora",
        ["logs.colLevel"] = "Nivel",
        ["logs.colModule"] = "Módulo",
        ["logs.colMessage"] = "Mensaje",
        ["logs.summary"] = "Resumen de logs",
        ["logs.totalToday"] = "Total de eventos hoy",
        ["logs.lastUpdate"] = "Última actualización",
        ["logs.firstToday"] = "Primer evento hoy",
        ["logs.copy"] = "📋 Copiar logs",
        ["logs.clear"] = "🗑 Limpiar",
        ["logs.showingPre"] = "Mostrando",
        ["logs.showingPost"] = "entradas",

        // Remote Bridge
        ["bridge.title"] = "Remote Print Bridge",
        ["bridge.subtitle"] = "Recibí trabajos de impresión desde un backend remoto. El agente se conecta hacia afuera — no abre puertos públicos.",
        ["bridge.enable"] = "Habilitar Remote Print Bridge",
        ["bridge.enableSub"] = "Cuando está desactivado el agente no intenta conectarse a ningún servidor externo.",
        ["bridge.serverUrl"] = "URL del servidor",
        ["bridge.agentId"] = "AgentId",
        ["bridge.apiKey"] = "API key",
        ["bridge.mode"] = "Modo",
        ["bridge.autoReconnect"] = "Reconectar automáticamente",
        ["bridge.save"] = "Guardar y aplicar",
        ["bridge.testConnection"] = "Probar conexión",
        ["bridge.lastConnection"] = "Última conexión:",
        ["bridge.serverUrlHint"] = "URL base del servidor. Ejemplo: https://api.tudominio.com",
        ["bridge.agentIdHint"] = "Identificador único de este agente en el servidor.",
        ["bridge.modeLabel"] = "Modo de conexión",
        ["bridge.modeSignalr"] = "SignalR (recomendado)",
        ["bridge.modePolling"] = "Polling HTTP",
        ["bridge.pollingInterval"] = "Intervalo de polling (segundos)",
        ["bridge.autoReconnectFull"] = "Reconectar automáticamente si se pierde la conexión",

        // Cliente (impresión remota)
        ["client.title"] = "Impresión remota (modo cliente)",
        ["client.subtitle"] = "Convertí impresoras de otra máquina en impresoras locales. Cualquier app imprime con Ctrl+P y el trabajo viaja por el hub hasta la impresora real del agente principal. No requiere drivers de fabricante.",
        ["client.enable"] = "Habilitar modo cliente",
        ["client.enableSub"] = "Levanta un servidor de impresión local (IPP) que reenvía los trabajos al hub.",
        ["client.ippPort"] = "Puerto IPP local",
        ["client.serverRunning"] = "Servidor IPP activo",
        ["client.serverStopped"] = "Servidor IPP detenido",
        ["client.save"] = "💾 Guardar",
        ["client.testHub"] = "🔌 Probar hub",
        ["client.hubHint"] = "Usa la misma URL y API key del hub configuradas en Remote Bridge.",
        ["client.virtualPrinters"] = "Impresoras virtuales",
        ["client.new"] = "+ Nueva",
        ["client.edit"] = "Editar",
        ["client.remove"] = "Quitar",
        ["client.editTitle"] = "Editar impresora virtual",
        ["client.newTitle"] = "Nueva impresora virtual",
        ["client.localName"] = "Nombre local (como aparece en Windows)",
        ["client.targetAgent"] = "Agente principal destino (AgentId)",
        ["client.targetPrinter"] = "Impresora en el principal (opcional)",
        ["client.route"] = "o Ruta/propósito (opcional)",
        ["client.targetHint"] = "Indicá una impresora explícita (ej. 'Cocina') o una ruta configurada en el principal (ej. 'kitchen_order').",
        ["client.installedBadge"] = "✓ En Windows",
        ["client.install"] = "🪟 Instalar en Windows",
        ["client.uninstall"] = "Quitar de Windows",
        ["client.provisionHint"] = "Instalar/Quitar crea o borra la impresora en Windows (requiere permisos de administrador).",
        ["client.saveBtn"] = "Guardar",
        ["client.cancelBtn"] = "Cancelar",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        // Common
        ["common.save"] = "Save",
        ["common.cancel"] = "Cancel",
        ["common.edit"] = "Edit",
        ["common.delete"] = "Delete",
        ["common.remove"] = "Remove",
        ["common.new"] = "New",
        ["common.test"] = "Test",

        // Sidebar / nav
        ["sidebar.subtitle"] = "Print Agent",
        ["sidebar.active"] = "Agent active",
        ["sidebar.version"] = "Version",
        ["sidebar.port"] = "Port",
        ["nav.dashboard"] = "Dashboard",
        ["nav.printers"] = "Printers",
        ["nav.routes"] = "Routes",
        ["nav.settings"] = "Settings",
        ["nav.logs"] = "Logs",
        ["nav.bridge"] = "Remote Bridge",
        ["nav.client"] = "Remote Printing",

        // Footer
        ["footer.secure"] = "Secure & local",
        ["footer.listening"] = "The agent listens on",
        ["footer.bydefault"] = "by default",
        ["footer.apiGuide"] = "📖 API Guide",
        ["footer.minimize"] = "⊟ Minimize",
        ["footer.exit"] = "⏻ Exit",

        // Dashboard
        ["dash.title"] = "Dashboard",
        ["dash.subtitle"] = "Print agent overview.",
        ["dash.agentStatus"] = "Agent status",
        ["dash.runningOk"] = "The agent is running correctly.",
        ["dash.httpPort"] = "HTTP Port",
        ["dash.version"] = "Version",
        ["dash.localUrl"] = "Local URL",
        ["dash.status"] = "Status",
        ["dash.quickActions"] = "Quick actions",
        ["dash.copyUrl"] = "Copy URL",
        ["dash.copyEndpoint"] = "Copy endpoint",
        ["dash.printTest"] = "Print test",
        ["dash.printersDetected"] = "Detected printers",
        ["dash.viewAll"] = "View all →",
        ["dash.routesConfigured"] = "Configured routes",
        ["dash.recentEvents"] = "Recent events",
        ["dash.viewLogs"] = "View logs →",
        ["dash.quickSummary"] = "Quick summary",
        ["dash.active"] = "Active",
        ["dash.uptime"] = "Uptime",
        ["dash.printers"] = "Printers",
        ["dash.noPrinter"] = "(no printer)",

        // Printers
        ["printers.title"] = "Installed printers",
        ["printers.subtitle"] = "Manage your printers: detect, test and set the default one.",
        ["printers.refresh"] = "↻ Refresh list",
        ["printers.setDefault"] = "⊕ Set as default",
        ["printers.printTest"] = "🖨 Print test",
        ["printers.colName"] = "Name",
        ["printers.colStatus"] = "Status",
        ["printers.colType"] = "Type",
        ["printers.colCaps"] = "Capabilities",
        ["printers.colDefault"] = "Default",
        ["printers.colActions"] = "Actions",
        ["printers.online"] = "Online",
        ["printers.defaultBadge"] = "✓ Default",
        ["printers.detailTitle"] = "Printer details",
        ["printers.selectPrompt"] = "Select a printer to see its details",
        ["printers.capsSupported"] = "Supported capabilities",
        ["printers.defaultYes"] = "✓ Yes",
        ["printers.source"] = "Source",
        ["printers.setDefaultBtn"] = "★ Set as default",

        // Routes
        ["routes.title"] = "Routes by purpose",
        ["routes.subtitle"] = "Each purpose sends content to a specific printer in the right format.",
        ["routes.new"] = "+ New route",
        ["routes.edit"] = "Edit",
        ["routes.test"] = "Test",
        ["routes.delete"] = "Delete",
        ["routes.colPurpose"] = "Purpose",
        ["routes.colPrinter"] = "Printer",
        ["routes.colType"] = "Type",
        ["routes.colStatus"] = "Status",
        ["routes.colActions"] = "Actions",
        ["routes.active"] = "Active",
        ["routes.unassigned"] = "(unassigned)",
        ["routes.selectPrompt"] = "Select a route to see its details",
        ["routes.editTitle"] = "Edit route",
        ["routes.newTitle"] = "New route",
        ["routes.purposeLabel"] = "Purpose",
        ["routes.purposeHint"] = "Letters, numbers and underscores only",
        ["routes.printerLabel"] = "Printer",
        ["routes.typeLabel"] = "Content type",
        ["routes.detailTitle"] = "Selected route details",
        ["routes.saveBtn"] = "Save route",
        ["routes.cancelBtn"] = "Cancel",
        ["routes.footerHint"] = "💡 Examples: ticket, kitchen_order, report, label, fiscal. Letters, numbers and underscores only.",
        ["routes.validations"] = "Recommended checks",
        ["routes.val1"] = "The purpose must be unique.",
        ["routes.val2"] = "The printer must be available.",
        ["routes.val3"] = "The type must match the app.",
        ["routes.testThis"] = "▷ Test this route",

        // Settings
        ["settings.title"] = "Agent settings",
        ["settings.subtitle"] = "Adjust the agent's network, security and startup preferences.",
        ["settings.network"] = "Network & connection",
        ["settings.networkSub"] = "Configure the agent's listening port.",
        ["settings.httpPort"] = "HTTP Port",
        ["settings.portHint"] = "The agent listens on 127.0.0.1 by default. Only local connections are accepted.",
        ["settings.cors"] = "CORS & allowed origins",
        ["settings.corsSub"] = "Define which websites can talk to the agent.",
        ["settings.allowCors"] = "Allow CORS",
        ["settings.origins"] = "Allowed origins (one per line)",
        ["settings.originsHint"] = "If the list is empty, any origin is allowed.",
        ["settings.startup"] = "Windows startup",
        ["settings.startupSub"] = "Controls behavior when the system starts.",
        ["settings.autostart"] = "Open automatically on Windows startup",
        ["settings.language"] = "Language",
        ["settings.languageSub"] = "Interface language.",
        ["settings.langEs"] = "Español",
        ["settings.langEn"] = "English",
        ["settings.save"] = "Save changes",

        // Logs
        ["logs.title"] = "Agent logs",
        ["logs.subtitle"] = "Review the agent's activity for diagnostics and troubleshooting.",
        ["logs.level"] = "Level:",
        ["logs.all"] = "All",
        ["logs.info"] = "Info",
        ["logs.warning"] = "Warning",
        ["logs.error"] = "Error",
        ["logs.autoRefresh"] = "Auto-refresh",
        ["logs.colTime"] = "Date / Time",
        ["logs.colLevel"] = "Level",
        ["logs.colModule"] = "Module",
        ["logs.colMessage"] = "Message",
        ["logs.summary"] = "Logs summary",
        ["logs.totalToday"] = "Total events today",
        ["logs.lastUpdate"] = "Last update",
        ["logs.firstToday"] = "First event today",
        ["logs.copy"] = "📋 Copy logs",
        ["logs.clear"] = "🗑 Clear",
        ["logs.showingPre"] = "Showing",
        ["logs.showingPost"] = "entries",

        // Remote Bridge
        ["bridge.title"] = "Remote Print Bridge",
        ["bridge.subtitle"] = "Receive print jobs from a remote backend. The agent connects outbound — it doesn't open public ports.",
        ["bridge.enable"] = "Enable Remote Print Bridge",
        ["bridge.enableSub"] = "When disabled, the agent won't try to connect to any external server.",
        ["bridge.serverUrl"] = "Server URL",
        ["bridge.agentId"] = "AgentId",
        ["bridge.apiKey"] = "API key",
        ["bridge.mode"] = "Mode",
        ["bridge.autoReconnect"] = "Reconnect automatically",
        ["bridge.save"] = "Save and apply",
        ["bridge.testConnection"] = "Test connection",
        ["bridge.lastConnection"] = "Last connection:",
        ["bridge.serverUrlHint"] = "Server base URL. Example: https://api.yourdomain.com",
        ["bridge.agentIdHint"] = "Unique identifier of this agent on the server.",
        ["bridge.modeLabel"] = "Connection mode",
        ["bridge.modeSignalr"] = "SignalR (recommended)",
        ["bridge.modePolling"] = "HTTP Polling",
        ["bridge.pollingInterval"] = "Polling interval (seconds)",
        ["bridge.autoReconnectFull"] = "Reconnect automatically if the connection drops",

        // Client (remote printing)
        ["client.title"] = "Remote printing (client mode)",
        ["client.subtitle"] = "Turn printers from another machine into local printers. Any app prints with Ctrl+P and the job travels through the hub to the real printer on the principal agent. No manufacturer drivers required.",
        ["client.enable"] = "Enable client mode",
        ["client.enableSub"] = "Starts a local print server (IPP) that forwards jobs to the hub.",
        ["client.ippPort"] = "Local IPP port",
        ["client.serverRunning"] = "IPP server running",
        ["client.serverStopped"] = "IPP server stopped",
        ["client.save"] = "💾 Save",
        ["client.testHub"] = "🔌 Test hub",
        ["client.hubHint"] = "Uses the same hub URL and API key configured in Remote Bridge.",
        ["client.virtualPrinters"] = "Virtual printers",
        ["client.new"] = "+ New",
        ["client.edit"] = "Edit",
        ["client.remove"] = "Remove",
        ["client.editTitle"] = "Edit virtual printer",
        ["client.newTitle"] = "New virtual printer",
        ["client.localName"] = "Local name (as shown in Windows)",
        ["client.targetAgent"] = "Target principal agent (AgentId)",
        ["client.targetPrinter"] = "Printer on the principal (optional)",
        ["client.route"] = "or Route/purpose (optional)",
        ["client.targetHint"] = "Enter an explicit printer (e.g. 'Cocina') or a route configured on the principal (e.g. 'kitchen_order').",
        ["client.installedBadge"] = "✓ In Windows",
        ["client.install"] = "🪟 Install in Windows",
        ["client.uninstall"] = "Remove from Windows",
        ["client.provisionHint"] = "Install/Remove creates or deletes the printer in Windows (requires administrator permissions).",
        ["client.saveBtn"] = "Save",
        ["client.cancelBtn"] = "Cancel",
    };
}
